"""
AI-Noether: Polynomial normalization utilities

Uses Macaulay2 for polynomial comparison and normalization.
This is more reliable than sympy since we're already using M2 throughout.
"""

import subprocess
import tempfile
import os
from typing import List, Set, FrozenSet, Optional, Tuple


def check_polynomials_equivalent_m2(
    poly1: str,
    poly2: str,
    variables: List[str],
    m2_path: str = "/opt/homebrew/bin/M2"
) -> bool:
    """
    Check if two polynomials are equivalent (equal or negatives) using Macaulay2.
    
    When set to zero, p = 0 and -p = 0 are equivalent.
    """
    var_str = ", ".join(variables)
    
    script = f"""
R = QQ[{var_str}];
p1 = {poly1};
p2 = {poly2};
diff = p1 - p2;
summ = p1 + p2;
if diff == 0 or summ == 0 then print "EQUIVALENT" else print "DIFFERENT";
"""
    
    try:
        with tempfile.NamedTemporaryFile(mode='w', suffix='.m2', delete=False) as f:
            f.write(script)
            script_path = f.name
        
        result = subprocess.run(
            [m2_path, "--script", script_path],
            capture_output=True,
            text=True,
            timeout=10
        )
        
        os.unlink(script_path)
        return "EQUIVALENT" in result.stdout
        
    except Exception:
        return False


def filter_generators_m2(
    generators: List[str],
    remaining_axioms: List[str],
    targets: List[str],
    variables: List[str],
    m2_path: str = "/opt/homebrew/bin/M2"
) -> List[str]:
    """
    Filter out generators that are in the ideal generated by remaining axioms and targets.
    
    Uses Groebner basis reduction: if gen % I == 0, then gen ∈ I and contains no new information.
    This is stronger than just checking equality - it catches any generator that's implied
    by the known axioms and targets.
    
    Args:
        generators: List of generator polynomials to filter
        remaining_axioms: Axioms that were NOT removed
        targets: Target polynomials
        variables: List of variable names (for M2 ring definition)
        m2_path: Path to Macaulay2 executable
    
    Returns:
        Generators that are NOT in the ideal (i.e., contain new information)
    """
    if not generators:
        return generators
    
    # Combine axioms and targets into one list of "known" polynomials
    known_polys = list(remaining_axioms) + list(targets)
    
    if not known_polys:
        return generators
    
    var_str = ", ".join(variables)
    known_list = ", ".join(known_polys)
    
    # Build M2 script to check ideal membership via Groebner basis reduction
    script_lines = [
        f"R = QQ[{var_str}];",
        "",
        "-- Define ideal from known polynomials (axioms + targets)",
        f"knownIdeal = ideal({known_list});",
        "",
        "-- Check each generator for ideal membership",
    ]
    
    for i, gen in enumerate(generators):
        # Check if gen % knownIdeal == 0 (i.e., gen is in the ideal)
        # Also check -gen in case of sign differences
        script_lines.append(f"gen{i} = {gen};")
        script_lines.append(f"rem{i} = gen{i} % knownIdeal;")
        script_lines.append(f"remNeg{i} = (-gen{i}) % knownIdeal;")
        script_lines.append(f'if rem{i} == 0 or remNeg{i} == 0 then print "GEN_{i}_IN_IDEAL" else print "GEN_{i}_NEW";')
    
    script = "\n".join(script_lines)
    
    try:
        with tempfile.NamedTemporaryFile(mode='w', suffix='.m2', delete=False) as f:
            f.write(script)
            script_path = f.name
        
        result = subprocess.run(
            [m2_path, "--script", script_path],
            capture_output=True,
            text=True,
            timeout=120  # Longer timeout for Groebner basis computation
        )
        
        os.unlink(script_path)
        
        # Parse output to find which generators contain new information
        kept = []
        for i, gen in enumerate(generators):
            if f"GEN_{i}_NEW" in result.stdout:
                kept.append(gen)
        
        return kept
        
    except Exception as e:
        # On error, return all generators (conservative)
        return generators


def normalize_generators_m2(
    generators: List[str],
    variables: List[str],
    m2_path: str = "/opt/homebrew/bin/M2"
) -> List[str]:
    """
    Normalize generators to canonical form using Macaulay2.
    
    This expands and simplifies each polynomial.
    """
    if not generators:
        return []
    
    var_str = ", ".join(variables)
    
    script_lines = [
        f"R = QQ[{var_str}];",
        "",
    ]
    
    for i, gen in enumerate(generators):
        script_lines.append(f'print("NORM_{i}:" | toString({gen}));')
    
    script = "\n".join(script_lines)
    
    try:
        with tempfile.NamedTemporaryFile(mode='w', suffix='.m2', delete=False) as f:
            f.write(script)
            script_path = f.name
        
        result = subprocess.run(
            [m2_path, "--script", script_path],
            capture_output=True,
            text=True,
            timeout=30
        )
        
        os.unlink(script_path)
        
        # Parse normalized forms
        normalized = []
        for i, gen in enumerate(generators):
            marker = f"NORM_{i}:"
            for line in result.stdout.split('\n'):
                if marker in line:
                    norm = line.split(marker)[1].strip()
                    normalized.append(norm)
                    break
            else:
                # If not found, use original
                normalized.append(gen)
        
        return normalized
        
    except Exception:
        return generators


def get_canonical_form_m2(
    poly: str,
    variables: List[str],
    m2_path: str = "/opt/homebrew/bin/M2"
) -> str:
    """
    Get canonical form of a single polynomial using Macaulay2.
    Also normalizes sign (makes leading coefficient positive).
    """
    var_str = ", ".join(variables)
    
    script = f"""
R = QQ[{var_str}];
p = {poly};
-- Get leading coefficient
lc = leadCoefficient p;
-- If negative, negate the polynomial
if lc < 0 then p = -p;
print("CANONICAL:" | toString(p));
"""
    
    try:
        with tempfile.NamedTemporaryFile(mode='w', suffix='.m2', delete=False) as f:
            f.write(script)
            script_path = f.name
        
        result = subprocess.run(
            [m2_path, "--script", script_path],
            capture_output=True,
            text=True,
            timeout=10
        )
        
        os.unlink(script_path)
        
        for line in result.stdout.split('\n'):
            if "CANONICAL:" in line:
                return line.split("CANONICAL:")[1].strip()
        
        return poly
        
    except Exception:
        return poly


# For backwards compatibility and non-M2 contexts, keep simple string-based versions

def normalize_polynomial_string(poly_str: str) -> str:
    """
    Simple string-based normalization (fallback when M2 not available).
    Just removes whitespace and sorts terms alphabetically.
    """
    # Remove whitespace
    s = poly_str.replace(' ', '')
    return s


def get_normalized_polynomial_set(polynomials: List[str]) -> FrozenSet[str]:
    """
    Get a normalized frozenset representation of a list of polynomials.
    Uses simple string normalization for set operations.
    """
    return frozenset(normalize_polynomial_string(p) for p in polynomials)

